# Generated by Django 5.1.7 on 2025-03-10 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200, unique=True)),
                ('descriere', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriere', models.TextField()),
                ('data_examen', models.DateTimeField()),
                ('materie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studybuddyapp.materie')),
            ],
        ),
        migrations.CreateModel(
            name='Proiect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('materie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studybuddyapp.materie')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=150)),
                ('descriere', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('materie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studybuddyapp.materie')),
            ],
        ),
    ]
